### ISSUE TITLE
Create 'templates' directory w/ example project declaration, etc.

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#1]
Would go in the top level directory, i.e. alongside docs/, aospy/, setup.py, etc.

So that user has an example/template for how to create a Proj object.  Part of larger effort to remove user-specific things from the codebase itself.  

Could also potentially include templates for creating Region objects, Calc objects, and Var objects, assuming those objects also get moved outside of the main codebase.

**Comment by spencerahill** [comment]
The templates/ directory now exists and includes example main.py and plot.py scripts.  Need to also populate it with example Proj, Calc, Var, Region, Unit object declarations.

**Comment by spencerahill** [comment]
Such templates should also be included in the User's guide/documentation, whenever that gets created.  Probably makes sense to move this directory in with the rest of the documentation when that occurs.  Also, the existing main.py and plot.py scripts are totally outdated at this point; up-to-date versions have been migrated to the [aospy-obj-lib repo](https://github.com/spencerahill/aospy-obj-lib).

**Comment by spencerahill** [comment]
@spencerkclark is working on some Jupyter Notebooks to go here.  The sample netCDF data and aospy objects are in https://github.com/spencerahill/aospy/tree/develop/aospy/test/data/netcdf and https://github.com/spencerahill/aospy/tree/develop/aospy/test/data/objects

@spencerkclark, as part of that, please rename this directory "examples" put your notebooks here, and delete the existing `plot.py` and `main.py` files.  Ultimately, I would like to include those templates, but for now they are out of date and so more harmful than beneficial to new users who would try to use them.

Also, do we need test/test_objs anymore?  If not, let's remove as part of that PR.

**Comment by spencerkclark** [comment]
> Also, do we need test/test_objs anymore? If not, let's remove as part of that PR.

They are used by `test_roundtrip.py`, which obviously can't be run on Travis, so I agree I wouldn't have any issue removing both the test_objs directory and `test_roundtrip.py` altogether.  I suppose if we wanted to preserve their existence, we could put them in a separate repo.

**Comment by spencerahill** [comment]
Let's just remove them, and if we really need them we can just grab them from any commit prior to this one. Thanks!

**Comment by spencerahill** [comment]
Closed by #106 and subsequent
