### ISSUE TITLE
Allow user to specify analysis period as a range of dates, rather than years

### ISSUE THREAD

**Issue by spencerkclark** [spencerahill/aospy#11]
Currently when constructing a `Run` object the user must specify a set of years that the model is run through as well as the analysis period.  For example:

``` python
am2_control = Run(
    name='am2_control',
    description=(
        'Preindustrial control simulation.'
        ),
    direc_nc=('/path/to/files'),
    nc_dur=100,
    nc_start_yr=1,
    nc_end_yr=100,
    default_yr_range=(21,100)
)
```

This works when the analysis period and  `Run` align nicely with years, but prevents any finer control.  Perhaps a solution that would provide greater flexibility would be to allow the user to specify the `default_time_range`.  For the above example it would be something along the lines of:

``` python
from netCDF4.netcdftime import datetime

am2_control = Run(
    name='am2_control',
    description=(
        'Preindustrial control simulation.'
        ),
    direc_nc=('/path/to/files'),
    nc_dur=100,
    nc_start_yr=1,
    nc_end_yr=100,
    default_time_range=(datetime(21, 1, 1), datetime(100, 12, 31))
)
```

Here instead of `numpy.datetime64` objects we can use [`netCDF4.netcdftime.datetime`](http://netcdf4-python.googlecode.com/svn/trunk/docs/netcdftime.netcdftime.datetime-class.html) objects which allow for years less than 1678.  For idealized cases with no natural calendar (which aospy currently treats as having a 360_day calendar) one could simply compute the start and end dates using the [`netCDF4.netcdftime.num2date`](http://netcdf4-python.googlecode.com/svn/trunk/docs/netcdftime.netcdftime-module.html#num2date) function based on the number of days since the start of the run.

**Comment by spencerahill** [comment]
This is in general a solid solution.

In fact, it seems superfluous to have both `_yr` and `_date` variants of these kwargs.  So I am inclined to replace the former with the latter, i.e. the kwargs would be `nc_start_date`, `nc_end_date`, and `default_time_range`.  If passed an integer, a `datetime` object (of the netCDF4 variety; see below) is generated assuming January 1 of that year.

Re: which datetime object to use, it seems to me that `netCDF4.netcdftime.datetime` is the way to go, given the year 0001, etc. considerations.  Doesn't add any new dependencies and resolves that problem.  Good find!

This would not be backwards compatible: you and I (confidently assuming we are still the only users) would have to change these in the objects we have already.  But I think it's worth the trouble -- shouldn't worry about legacy code at this early, volatile stage of the project.

**Comment by spencerahill** [comment]
As of the most recent commit to the `xray` branch (3ebb63f64528aad4ff16b30115eb045e708af8a5), this has been implemented, in that `_yr` kwargs/attributes have been replaced with `_date` variants, with `datetime.datetime` objects being used primarily rather than integers corresponding to years.  The `TimeManager` class and `timedate` module have been added to handle time- and date-related computations.

However, I have not yet tested it yet for non-vanilla times, i.e. years < 1678 or not spanning full months/years.  So not quite ready to close the issue yet, not until we write some tests that demonstrate the new stuff actually works for all of our use cases.

**Comment by spencerkclark** [comment]
Yes, I've just tested a case under the `xray` branch with years < 1678; there are some bugs.  Once I get things sorted out I'll create a pull-request.

**Comment by spencerahill** [comment]
@spencerkclark Does the code you implemented in the above pull request fix the bugs you came across?  If yes, I'll close this issue.

**Comment by spencerkclark** [comment]
Yes, the code I implemented fixes the issues I was having.  I'll go ahead and close it.
