### ISSUE TITLE
v0.1 release on conda-forge

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#112]
However far along we get in the refactor, I think it's important to have pip- and conda-installable v0.1 releases of aospy before I present it at the AMS meeting on Jan. 24.  That will add credibility to it when I present.

Will wait until the week preceding to do this, so that we can get as much in in the meantime, but wanted a thread open to track the progress/discuss as necessary.  First step would be pip, then conda.

pypi instructions: https://packaging.python.org/distributing/#uploading-your-project-to-pypi

**Comment by spencerahill** [comment]
PyPI machinery is now in place via #115 (once it is merged).  conda next...

**Comment by spencerahill** [comment]
conda-forge submission instructions: https://conda-forge.github.io/#add_recipe

But we need to formally release on Github first (to generate the SHA and URL, which I'll do at the same time as the pip release.  Then once submit to conda-forge have to hear back from them, not sure what the turnaround will be.  So wouldn't necessarily count on this making it before AMS.  But otherwise looks pretty straightforward.

**Comment by spencerahill** [comment]
v0.1 release is done on Github and pypi, so will proceed with this, hopefully by end of this week

**Comment by spencerahill** [comment]
Submitted to conda-forge: https://github.com/conda-forge/staged-recipes/pull/2275

**Comment by spencerahill** [comment]
Minor conda-forge submission errors fixed and got greenlight from conda-forge devs on the merge as soon as their Travis CI build finishes.  So should be all set soon.

**Comment by spencerahill** [comment]
Although it looks like conda-forge has quite a backlog on Travis-CI: https://travis-ci.org/conda-forge/staged-recipes/builds

So it will probably be a few days before this is done.

**Comment by spencerkclark** [comment]
@spencerahill that's awesome!  Thanks for figuring out how to do that.

**Comment by spencerahill** [comment]
Done, but see #131 for problem with v0.1 that is fixed by #128, which will go into v0.1.1
