### ISSUE TITLE
Warn or except if specified date selection results in empty time array

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#114]
More than once, I have inadvertently instructed `Calc` to perform calculations over date ranges that do not intersect at all with the data that I have instructed it to load.  Currently, `Calc` doesn't warn or do anything about this, it just yields DataArrays with empty time dimensions, until it eventually crashes when trying to do time reductions.

It would be much better if `Calc` warned, or maybe even raised an error, when this happens.  I'm actually inclined for the latter -- there is no way that the calculation will go how you wanted it if you end up with an empty time coordinate, so might as well stop there.

Either way, this should be straightforward enough to implement.

**Comment by spencerkclark** [comment]
Very much agreed.  I think this is sort of just a special case of #72 (in which both sides of the specified time range are outside that of the dataset).  I think what I have so far in #90 should address this; there it would lead to an error.

**Comment by spencerahill** [comment]
>I think what I have so far in #90 should address this; there it would lead to an error.

Perfect!

**Comment by spencerahill** [comment]
Closed by #90
