### ISSUE TITLE
Make python versions supported (2.7, 3.4, 3.5, and 3.6) consistent across CI, setup.py, and conda releases

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#124]
Should be straightforward, c.f. https://github.com/pydata/xarray/pull/1183

**Comment by spencerahill** [comment]
Should also add 3.4 while we're at it

**Comment by spencerahill** [comment]
Currently, AppVeyor checks 2.7 and 3.4; Travis CI checks 2.7 and 3.5, and the conda-forge releases are for 2.7, 3.5, and 3.6 (see below).  All should be for 2.7 and 3.4-3.6.

```
conda search -c conda-forge aospy
Fetching package metadata .........
aospy                     *  0.1                      py27_0  conda-forge
                             0.1                      py35_0  conda-forge
                          .  0.1                      py36_0  conda-forge
```

**Comment by spencerahill** [comment]
conda-forge fix will be done within the staged-recipes/aospy repo; re-opening this until we're sure that's done

**Comment by spencerkclark** [comment]
@spencerahill would it be worth having AppVeyor use the same environment configuration files (e.g. ```ci/environment-py27.yml```) that Travis does to setup its test environments?  That way we're guaranteed consistency across the platforms.  

If you think that would be worth it, I can try putting together a quick PR; I think it should be pretty straightforward.

**Comment by spencerahill** [comment]
Sorry for the delay in responding to this.  Sure, feel free to do this if you'd like.

Sorry also for the delay on v0.1.1 -- I've managed to overwhelm myself with other stuff.  I'll try to put out the v0.1.1rc1 on PyPI soon.

**Comment by spencerkclark** [comment]
No worries, I'm perfectly fine taking our time with things.  I'll put together a PR later today regarding my comment above.  For a little more context, I'd like to get things working here first, and then possibly address the same issue in xarray (pydata/xarray#1127); I think it may solve the AppVeyor failures I'm getting on the NetCDFTimeIndex PR.

**Comment by spencerahill** [comment]
Sounds good.  Thanks!

**Comment by spencerahill** [comment]
v0.1.1 is officially released: https://github.com/spencerahill/aospy/releases/tag/v0.1.1
And on pypi: https://pypi.org/project/aospy/

Unfortunately, it looks like we need to add the `cloudpickle` dependency of `dask` to setup.py.  If you try `pip install aospy` without having first installed `cloudpickle`, the test_calc_basic tests all fail with an ImportError.  The immediate workaround is `pip install cloudpickle aospy` -- then everything works.

I submitted the PR for the conda-forge update before I caught this: https://github.com/conda-forge/aospy-feedstock/pull/1.  Waiting for the CI to finish, but my guess/hope is that this cloudpickle installation is handled automatically by the conda install and thus isn't a problem.

I added cloudpickle to setup.py in 0c4b351, so this won't be an issue for any subsequent releases.  In the meantime, we just need to make note of this in the docs.  Unfortunately though, readthedocs builds are currently failing due to an internal RTD problem: https://github.com/rtfd/readthedocs.org/issues/2651, so it won't be reflected on the docs themselves until that's resolved.  

I've added a quickstart section to our README in 586e7a1984d4068f537a4de01d19c90b055bb482 noting this temporary installation quirk.

**Comment by spencerkclark** [comment]
Good catch!  Thanks for updating things to reflect that dependency.  No big deal that installing via pip will require a bit of extra work for this release.  I agree, hopefully the conda option will take care of things automatically.

**Comment by spencerahill** [comment]
conda build completed and works as we hoped: conda install -c conda-forge aospy gets you v0.1.1 with all needed dependencies and tests pass.

However, I realized after the fact that the conda build skipped python 3.4.  So re-configured our feedstock (=the repo where we submit new builds for inclusion in conda-forge) to include it: https://github.com/conda-forge/aospy-feedstock/pull/2.  Unfortunately this means likely another couple days due to conda-forge's backlog on Travis CI.

**Comment by spencerahill** [comment]
Actually the build finished already (maybe new builds w/out version change get expedited, or just the backlog lessened) and 3.4 is working:

```
$ conda search aospy
Fetching package metadata .........
aospy                     .  0.1                      py27_0  conda-forge
                             0.1                      py35_0  conda-forge
                          .  0.1                      py36_0  conda-forge
                             0.1.1                    py27_0  conda-forge
                             0.1.1                    py35_0  conda-forge
                          .  0.1.1                    py36_0  conda-forge
                             0.1.1                    py27_1  conda-forge
                             0.1.1                    py34_1  conda-forge
                             0.1.1                    py35_1  conda-forge
                             0.1.1                    py36_1  conda-forge
```

So closing, although see #127 re: blocker to v0.1.1 announcements due to RTD doc builds failing
