### ISSUE TITLE
Add example_obj_lib.py file using objects from tutorial.ipynb and use in main script

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#151]
Essentially just copy and paste the object definitions in examples.ipynb into a separate .py file that is itself a functional aospy object library.  That way users have a direct example of a working object library file from the outset that they can copy elsewhere and manipulate, rather than having to cut and paste from a notebook.

Also, we should populate the main script with this object library, such that users can submit the main script and execute example calculations immediately upon installing aospy.

**Comment by spencerahill** [comment]
Re-opening because, although #155 created the example_obj_lib.py file, I haven't yet updated the notebook (which I will rename from example.ipynb to tuotiral.ipynb) to use this package.

**Comment by spencerahill** [comment]
(edited for clarity)

Slight hiccup: the examples section of the docs, which gets compiled with $CWD being `aospy/docs`, is unable to do `import example_obj_lib`, because the latter is located in `aospy/aospy/examples`.  A workaround is to `cd` to the examples directory.  

This is because `example_obj_lib.py` is not technically included in aospy (via `__init__.py`) nor has it been installed otherwise, so it can only be imported from that directory.  Unless there's a way to import modules not on PYTHONPATH from directories other than the current one?

Another option: this could be avoided if we explicitly included the example library in aospy: `aospy.examples.example_obj_lib`.

@spencerkclark any thoughts?  Hope I'm being clear enough.

**Comment by spencerkclark** [comment]
@spencerahill are you referring to this page? http://aospy.readthedocs.io/en/latest/examples.html

**Comment by spencerkclark** [comment]
Are you trying to add an example of using the main script there (which I assume would benefit from using ```example_obj_lib```)?  I just want to make sure I understand, because while it needs to be updated for the updated ```calc.py```, currently that page does not rely on ```example_obj_lib```.

**Comment by spencerkclark** [comment]
Could creating a symbolic link to ```example_obj_lib.py``` in ```aospy/docs``` work?

```
(aospy-dev) bash-4.1$ ln -s ../aospy/examples/example_obj_lib.py example_obj_lib.py
(aospy-dev) bash-4.1$ ipython
Python 3.6.0 | packaged by conda-forge | (default, Feb  9 2017, 14:36:55)
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import example_obj_lib
```

That feels kind of hacky though.  What do you think?

**Comment by spencerahill** [comment]
>Are you trying to add an example of using the main script there (which I assume would benefit from using example_obj_lib)

Yes, or at least `example_obj_lib` and `submit_mult_calcs`.  The problem is that, even if I re-define all of the needed objects locally within the examples page, an object library is required for the `calc_suite_specs['library']` field.  (This is what motivated #163; then we could just define the ObjLib object locally and not have this problem.)

Nice idea re: symbolic link.  Another option is interactively adding the examples directory to PYTHONPATH via `os` (or maybe `sys`).

**Comment by spencerahill** [comment]
The least hack-ish option to me is to actually add `example_obj_lib.py` to aospy via `aospy.__init__`, such that it's accessible via `from aospy.examples import example_obj_lib`.  I would keep the `examples` layer, rather than `aospy.example_obj_lib`, because that keeps the top-level namespace cleaner and allows us to add more examples later in a clean way if we want.

We could also include `aospy_main.py`, although I don't see the benefit, since we don't need anything from it in the same way we need `example_obj_lib` here.

**Comment by spencerkclark** [comment]
I agree; I think doing that would be perfectly fine.

> We could also include aospy_main.py, although I don't see the benefit, since we don't need anything from it in the same way we need example_obj_lib here.

Yeah, I say hold off on adding anything else until we explicitly need it.

**Comment by spencerahill** [comment]
@spencerkclark perfect, going this route.

**Comment by spencerkclark** [comment]
@spencerahill also there are a couple spots in the tutorial notebook that need to be changed now that it's been moved to a new directory.  I can create a pull request tomorrow if you'd like.

**Comment by spencerahill** [comment]
@spencerkclark I noticed some also.  I'll have a PR in by the end of the night; feel free to push anything that I missed once it's up.
