### ISSUE TITLE
Use pytest-ipynb to test tutorial notebook

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#162]
Copying https://github.com/spencerahill/aospy/pull/161#issuecomment-289839933:

>Any interest in checking out pytest-ipynb to have Travis always check to make sure the example notebook runs? I came across it yesterday, as it's used in OceanPARCELS/parcels in their Travis build process: https://travis-ci.org/OceanPARCELS/parcels/builds/191243567

This looks cool, and we should get it to work.

**Comment by spencerkclark** [comment]
Credit to @nathanieltarshish for pointing me to this yesterday.

**Comment by spencerahill** [comment]
Closed by #166 (although we ultimately went with IPython and runipy rather than pytest-ipynb)
