### ISSUE TITLE
Overflow in time averaging

### ISSUE THREAD

**Issue by spencerkclark** [spencerahill/aospy#17]
Due to the fact that within `xray.DataArray` objects, timedeltas are always stored as `timedelta64[ns]` (regardless of whether you instantiate the DataArray with `timedelta64[D]` or `timedelta64[Y]` objects), they tend to be very large numbers.  In particular, when grouping by years and summing, these numbers are on the order of 10^16.  Even for relatively small numbered-data (like temperature, which is order 100) this can lead to overflow issues (which go undetected until you look at the results of a computation; you end up getting negative values for weighted averages).  

Here's a minimal working example of the problem:

```
In [1]: import xray
In [2]: import numpy as np
In [3]: year = xray.DataArray(np.timedelta64(1,'Y'))
In [4]: print(year)
<xray.DataArray ()>
numpy.timedelta64(31556952000000000,'ns')

# For small numbers this works.
In [5]: year * 100
Out[5]:
<xray.DataArray ()>
numpy.timedelta64(3155695200000000000,'ns')

# For larger numbers things turn negative.  This is not good, because if you 
# were taking the annual average at a gridbox where the average value was 300
# you would have a number like this in the numerator within _to_yearly_ts().
In [6]: year * 300
Out[6]:
<xray.DataArray ()>
numpy.timedelta64(-8979658473709551616,'ns')
```

An easy fix is to simply scale and convert the `dt` array such that instead of being comprised of `timedelta64[ns]` objects, it is instead comprised of `float` objects with the value represented by the timedelta, but in number of days rather than nanoseconds.  The main issue I see with this solution is that if there were ever some place where we needed a particular feature of a timedelta (other than its number), then we wouldn't have it, but since the values would still be in a `xray.DataArray` they would still be linked with the time coordinate.

Is there any need for the functionality of the timedeltas once they exist, or can we just convert `dt` to being a DataArray of `float` objects?

A solution within `_to_yearly_ts` could look like

``` python
def _to_yearly_ts(self, arr, dt):
        """Average a sub-yearly time-series over each year."""
        if isinstance(dt, int):
            dt_by_year = len(arr.groupby('time.year'))
        else:
            # Convert from ns to days (prevent overflow)
            dt.values = dt.values.astype('timedelta64[D]').astype('float')
            dt_by_year = dt.groupby('time.year').sum('time')  
        arr = arr*dt
        return arr.groupby('time.year').sum('time') / dt_by_year
```

but perhaps we could just change `self.dt` at the very beginning when we bring it in (say in `_create_input_data_obj`?).

**Comment by spencerahill** [comment]
Nice catch.  I had noticed this behavior too, but it was while I was overhauling things, so I thought it resulted from a mistake I had made elsewhere!

The fix you implemented seems good.  Do we maybe want a unit of hours, however, rather than days?  Since often I use e.g. 3 hourly data.  On the other hand, if decimal-values of the base unit work properly, then this doesn't matter.  (I would assume they do.)

**Comment by spencerkclark** [comment]
Good call.  We either need to convert to decimal values, or use a smaller base unit; a simple test shows that the above solution fails for time increments less than a day:

```
In [1]: hour = xray.DataArray(np.timedelta64(3600, 's'))
In [2]: hour.astype('timedelta64[D]').astype('float')
Out[2]:
<xray.DataArray ()>
array(0.0)
```

Come to think of it, I think the issue with `np.timedelta64` objects is that they are signed 64-bit integers, which places a tighter limit on their maximum values (something on the order of 10^18 or 10^19).  If we just convert the DataArray to have type `float` (and don't bother with scaling) I think we might be OK, since a float has a maximum value of something on the order of 10^308.  

``` python
def _to_yearly_ts(self, arr, dt):
        """Average a sub-yearly time-series over each year."""
        if isinstance(dt, int):
            dt_by_year = len(arr.groupby('time.year'))
        else:
            # Convert to float to prevent overflow
            dt = dt.astype('float')
            dt_by_year = dt.groupby('time.year').sum('time')  
        arr = arr*dt
        return arr.groupby('time.year').sum('time') / dt_by_year
```

**Comment by spencerahill** [comment]
Converting to floats is fine; however I think we should first convert to seconds (simply because that's the SI unit for time).  In fact, performing this conversion using the numpy API results in an array of floats anyways:

```
In [38]: print(dt)
<xray.DataArray 'average_DT' (time: 12)>
array([2678400000000000, 2419200000000000, 2678400000000000,
       2592000000000000, 2678400000000000, 2592000000000000,
       2678400000000000, 2678400000000000, 2592000000000000,
       2678400000000000, 2592000000000000, 2678400000000000], dtype='timedelta64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1983-01-16T12:00:00 1983-02-15 ...
Attributes:
    long_name: Length of average period

In [40]: dt.dtype
Out[40]: dtype('<m8[ns]')

In [42]: dt_sec = dt / np.timedelta64(1, 's')

In [44]: dt_sec
Out[44]:
<xray.DataArray 'average_DT' (time: 12)>
array([ 2678400.,  2419200.,  2678400.,  2592000.,  2678400.,  2592000.,
        2678400.,  2678400.,  2592000.,  2678400.,  2592000.,  2678400.])
Coordinates:
  * time     (time) datetime64[ns] 1983-01-16T12:00:00 1983-02-15 ...

In [45]: dt_sec.dtype
Out[45]: dtype('float64')
```

Admittedly, in this case of a time-average, the time units don't matter, provided they are consistent.  But in other applications, e.g. time tendencies, the time unit does matter, and should default to seconds.

(Maybe someday down the road we tack on physical units to DataArrays and enable automatic conversions, which I think you mentioned Iris does (and which `aospy.constants` crudely attempts).)

Are there other places in `aospy` where this overflow issue could potentially occur?  We should apply this `/ np.timedelta64(1, 's')` fix to each of them.

**Comment by spencerkclark** [comment]
Very nice -- I didn't realize that you could divide by a `timedelta` to convert to `floats` of the desired base unit.  As far as I know this is the only place where we use `dt` as a weighting in taking averages.

**Comment by spencerahill** [comment]
The commit b58c1c18132c5110bca16fd67a974398f4c0dda9 implements this.  It applies the conversion to seconds right when `self.dt` is set, which I think is best.

Also in this and preceding commits, I corrected a bug that affected the `dt` value for instantaneous data.  Now an array of ones is created with shape matching the time coordinate, removing the need for an if/else in  `_to_yearly_ts`.
