### ISSUE TITLE
operator.py module name conflicts with a standard library module's

### ISSUE THREAD

**Issue by spencerkclark** [spencerahill/aospy#174]
This is a somewhat obscure issue, but it came up today as I was updating my `emacs` configuration on the GFDL systems -- I now use [flycheck](http://www.flycheck.org/en/latest/) for doing syntax checking/linting of python, which depends on the [standard library's `operator` module](https://docs.python.org/3/library/operator.html).  When I edit files in the aospy repository, python tries to import aospy's version of the `operator` module, which causes problems for flycheck.

There are two simple solutions here:
1. Rename `aospy/operator.py` something else
2. Since we don't currently use any of the code in `aospy/operator.py`, we could remove it for now

@spencerahill what are your thoughts?  Should we try to fix this?

**Comment by spencerahill** [comment]
I'm in favor of removing it.  It was hacky to begin with, and I don't see any use for it on the horizon.  PR welcome :)
