### ISSUE TITLE
Incorrect temporal grouping when data's time array matches the end-dates of its time_bounds array

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#185]
[utils.times._assert_has_data_for_time](https://github.com/spencerahill/aospy/blob/develop/aospy/utils/times.py#L387) is meant to ensure that the data loaded from disk for a Calc actually contains data spanning the full range of times specified for that Calc.  It uses the `raw_start_date` and `raw_end_date` attributes of the data to perform this check if they're there.  These attributes are set by [ensure_time_avg_has_cf_metadata](https://github.com/spencerahill/aospy/blob/develop/aospy/utils/times.py#L306).  If they don't exist, it just pulls the first and last times from the array.

However, I have come across a case where this logic failed.  The case is monthly data whose netCDF files' time metadata is incorrect, creating an off-by-one error (i.e. the file corresponding to January of year 1 was being decoded to February of year 1, and so on).  Although this is easily fixed via the `input_time_offsets` kwarg to `submit_mult_calcs`, I didn't realize this at first, yet aospy didn't raise or warn.  Instead, the `raw_data_start_date` was set to what is *supposed* to be the start date, i.e. January of year 1, rather than the actual decoded start date, which is February of year 1.  Compare `raw_data_start_date` and `time` in the snippet of this repr:

```python
Coordinates:
  ...
  * time                 (time) datetime64[ns] 1678-02-01 1678-03-01 ...
    time_weights         (time) timedelta64[ns] 31 days 28 days 31 days ...
    raw_data_start_date  datetime64[ns] 1678-01-01
    raw_data_end_date    datetime64[ns] 1682-01-01
    subset_start_date    datetime64[ns] 1678-01-01
    subset_end_date      datetime64[ns] 1680-12-30
  ...
```

Since `_assert_data_for_time` uses `raw_data_{start,end}_date` if they're there, it erroneously doesn't raise.  @spencerkclark any thoughts on how best to fix this?

**Comment by spencerkclark** [comment]
@spencerahill does the original data have a time bounds variable?  If it exists, could I see what that looks like (both its values and attributes)?

**Comment by spencerahill** [comment]
Yes, it does, `time_bnds`:

```python
xr.open_dataset('~/Dropbox/projects/gms_natalie_burls/cam5_co2_runs_data/2x/abrupt2xCO2_T31_gx3v7.cam2.h0.0700-01.nc').time_bnds
/Users/shill/Dropbox/miniconda3/lib/python3.5/site-packages/xarray/conventions.py:389: RuntimeWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using dummy netCDF4.datetime objects instead, reason: dates out of range
  result = decode_cf_datetime(example_value, units, calendar)
/Users/shill/Dropbox/miniconda3/lib/python3.5/site-packages/xarray/conventions.py:408: RuntimeWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using dummy netCDF4.datetime objects instead, reason: dates out of range
  calendar=self.calendar)
Out[3]:
<xarray.DataArray 'time_bnds' (time: 1, nbnd: 2)>
array([[ 255135.,  255166.]])
Coordinates:
  * time     (time) object  700-02-01 00:00:00
Dimensions without coordinates: nbnd
Attributes:
    long_name: time interval endpoints
```

Here's also an ncdump -c of one of the files: https://gist.github.com/spencerahill/91a733f96ac69d9dc7aff34a94ed6de6

These are monthly averages, one month per file, with the total timeseries spanning several years.  And here's the actual netCDF file: https://dl.dropboxusercontent.com/u/25343175/abrupt2xCO2_T31_gx3v7.cam2.h0.0700-01.nc

**Comment by spencerahill** [comment]
>array([[ 255135.,  255166.]])

Hmm, so the time value is equal to the ending time bound:

```python
xr.open_dataset('cam5_co2_runs_data/2x/abrupt2xCO2_T31_gx3v7.cam2.h0.0700-01.nc', decode_cf=False).time.values
Out[6]: array([ 255166.])
```

But that value corresponds to Feb. 1 of year 700, hence the off-by-one.

**Comment by spencerkclark** [comment]
> Hmm, so the time value is equal to the ending time bound

I believe this is the same thing that happens with the time variable of GFDL model output (so it seems to be a fairly common issue).  From the looks of it, it appears that the time bounds are correct and don't need an offset (this is true with GFDL output too).

I'll need to think about this more;  I can't think of a clear way to avoid this problem.  Ultimately it would be more idiomatic to use something like a `PeriodIndex` or an `IntervalIndex` based completely on the more reliable time_bounds coordinate for the case of time average data, but neither option does everything we need (e.g. one currently can't save a DataArray to a netCDF file that contains a PeriodIndex, and an IntervalIndex composed of datetimes does not have field accessors to enable grouping by months, and can't be stored in a netCDF file).

**Comment by spencerahill** [comment]
>I believe this is the same thing that happens with the time variable of GFDL model output

At least not all GFDL model output:

```python
In [10]: ds = xr.open_dataset('/arch7/s1h/am2/am2clim_reyoi/gfdl.ncrc3-intel-prod/pp/atmos/ts/monthly/30yr/atmos.198301-201212.alb_sfc.nc', decode_cf=False)

In [12]: ds.time
Out[12]:
<xarray.DataArray 'time' (time: 360)>
array([   380.5,    410. ,    439.5, ...,  11238.5,  11269. ,  11299.5])
Coordinates:
  * time     (time) float64 380.5 410.0 439.5 470.0 500.5 531.0 561.5 592.5 ...
Attributes:
    long_name: time
    units: days since 1982-01-01 00:00:00
    cartesian_axis: T
    calendar_type: NOLEAP
    calendar: NOLEAP
    bounds: time_bounds

In [13]: ds.time_bounds
Out[13]:
<xarray.DataArray 'time_bounds' (time: 360, nv: 2)>
array([[   365.,    396.],
       [   396.,    424.],
       [   424.,    455.],
       ...,
       [ 11223.,  11254.],
       [ 11254.,  11284.],
       [ 11284.,  11315.]])
Coordinates:
  * nv       (nv) float64 1.0 2.0
  * time     (time) float64 380.5 410.0 439.5 470.0 500.5 531.0 561.5 592.5 ...
Attributes:
    long_name: time axis boundaries
    units: days
    missing_value: 1e+20
    _FillValue: 1e+20
```

This may be overdoing it, but what about overwriting the actual time array with the mean of the associated time bounds?  Or doing so whenever the time is the same as the ending bound?  That seems like it would work for this particular use case.

I can't think of a reason why time should ever correspond to anything /besides/ the mean of the bounds, at least once it gets fed into aospy.

**Comment by spencerahill** [comment]
In case it's not entirely clear already, the problem is that the ending times in the 'time_bounds' attribute are exclusive, meaning that the time period includes data up to the end date but not the end date itself.  E.g. for monthly averages, this means that the end date will be midnight of the first day of the following month.  In contrast, the time period is inclusive with respect to the start date.  I.e. time period = [start_date, end_date).

(This differs from our both-inclusive, [start_date, end_date] approach in aospy in e.g. the `date_ranges` kwarg to `submit_mult_calcs`.)

So when the time value is the same as this ending value, its 'month' value corresponds to one month ahead.  In other words, the problem amounts to the time value having a different month than the starting date of the corresponding time_bounds value: we can expect trouble if `not all(time.month == time_bound[0].month)` (that syntax might not be 100% correct).

**Comment by spencerkclark** [comment]
Sorry I didn't mean to imply all GFDL output suffers that problem; here's an analogous example to the CAM example:
```
In [2]: ds = xr.open_dataset('/archive/Spencer.Clark/imr_skc/control/gfdl.ncrc3-default-repro/1/history/00050101.atmos_month.nc', decode_times=False)

In [3]: ds.time_bounds
Out[3]:
<xarray.DataArray 'time_bounds' (time: 12, nv: 2)>
array([[ 1460.,  1491.],
       [ 1491.,  1519.],
       [ 1519.,  1550.],
       [ 1550.,  1580.],
       [ 1580.,  1611.],
       [ 1611.,  1641.],
       [ 1641.,  1672.],
       [ 1672.,  1703.],
       [ 1703.,  1733.],
       [ 1733.,  1764.],
       [ 1764.,  1794.],
       [ 1794.,  1825.]])
Coordinates:
  * time     (time) float64 1.491e+03 1.519e+03 1.55e+03 1.58e+03 1.611e+03 ...
  * nv       (nv) float64 1.0 2.0
Attributes:
    long_name:  time axis boundaries
    units:      days

In [4]: ds.time
Out[4]:
<xarray.DataArray 'time' (time: 12)>
array([ 1491.,  1519.,  1550.,  1580.,  1611.,  1641.,  1672.,  1703.,  1733.,
        1764.,  1794.,  1825.])
Coordinates:
  * time     (time) float64 1.491e+03 1.519e+03 1.55e+03 1.58e+03 1.611e+03 ...
Attributes:
    long_name:       time
    units:           days since 0001-01-01 00:00:00
    cartesian_axis:  T
    calendar_type:   NOLEAP
    calendar:        NOLEAP
    bounds:          time_bounds
```

> This may be overdoing it, but what about overwriting the actual time array with the mean of the associated time bounds?  Or doing so whenever the time is the same as the ending bound? That seems like it would work for this particular use case.

This didn't occur to me!  I think either of those are good options.  It does assume that the time bounds coordinate is *always* correct, but in my experience that has been the case.

**Comment by spencerahill** [comment]
>here's an analogous example to the CAM example

Thanks for that.  Wonder why the within-lab difference.  I wonder if it's an issue of idealized vs. comprehensive models.

>It does assume that the time bounds coordinate is always correct, but in my experience that has been the case.

Same.  I'll put together a PR implementing this (eventually :)).  I think I can generalize it so that it works for e.g. daily data too -- the condition is that we expect the start time of each period and the associated time value to have the same value at and below the temporal resolution of the data.  So for daily data, the year, month, and day should match.  For monthly, the year and month should match.  For yearly, the year should match.

**Comment by spencerahill** [comment]
If we go this route, would we want to revert back to the original timestamp after the calculations?  On the one hand, that might re-introduce these same complications for the user when they're subsequently using the aospy output during e.g. exploratory analysis.

On the other hand, not retaining the original is tantamount to making the actual time array redundant; it can be ascertained directly from the time bounds array.  Is there any reason why the original timestamp would be useful to have around?  Or might be useful in the future?

I'm slightly leaning towards option 1, i.e. not retaining the original, mostly just out of expediency.  But I could be convinced otherwise.

**Comment by spencerkclark** [comment]
> I'm slightly leaning towards option 1, i.e. not retaining the original, mostly just out of expediency. But I could be convinced otherwise.

I agree here; we should retain whichever time array is most accurate [whether that's the one originally in the data if no time bounds are present, or the time array inferred from the time bounds (meaning overwrite the original time array if it exists)].

**Comment by spencerahill** [comment]
Sounds good.  Since we're typically down-sampling in time anyways in terms of the final output, the original time array values seem to me even less relevant than I had originally thought.

Will put together a PR.
