### ISSUE TITLE
Towards v0.2 release

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#198]
I think we've added enough new features and fixed enough sufficiently important bugs to warrant our next 'major' release, namely v0.2.0.

I don't think it's been discussed anywhere, but in this pre v1.0 stage I'm essentially envisioning us following [xarray's versioning](https://github.com/pydata/xarray/blob/master/HOW_TO_RELEASE), i.e. a "light" version of [semantic versioning](http://semver.org):

>We follow a rough approximation of semantic version. Only major releases (0.X.0)
show include breaking changes. Minor releases (0.X.Y) are for bug fixes and
backwards compatible new features, but if a sufficient number of new features
have arrived we will issue a major release even if there are no compatibility
breaks.

>Once the project reaches a sufficient level of maturity for a 1.0.0 release, we
intend to follow semantic versioning more strictly.

I unwisely put a 'v0.2' milestone on many Issues that really deserve a 'v1.0' milestone instead.  So I will fix those.  Other than that, I'd say once #197 is in, let's go ahead.

Comments?

**Comment by spencerkclark** [comment]
Yes, that sounds good to me.  What do you think about adding #187 to our to-do list before releasing?  Is there still more to discuss there, or can I go ahead and make that suggested fix?  (The reason I ask is that fix is required for one of our users).

**Comment by spencerahill** [comment]
Good call.  #187 had fallen off my radar, but let's definitely get that in for v0.2.0.  Your fix there looks good.

**Comment by spencerahill** [comment]
FYI in terms of timeline, my goal is for the release by the end of September.  So no rush on #187 if you have more pressing concerns.

**Comment by spencerahill** [comment]
Also considering #185 as a blocker...that seems like a similarly important bug to fix.  As in it's likely to cause pain for a decent amount of users (e.g. anybody using CAM/CESM data).

**Comment by spencerahill** [comment]
>I unwisely put a 'v0.2' milestone on many Issues that really deserve a 'v1.0' milestone instead. So I will fix those.

This is now done; I created a 'before v1.0' milestone and moved most of the v0.2 Issues there.  So now we're left with #185 and #187 as the only blockers.

**Comment by spencerahill** [comment]
Another task: add PyAOS blogpost and PyCon mention to our docs

**Comment by spencerahill** [comment]
#185 and #197 now closed. Remaining:

- [x] #168
- [x] #187
- [x] Add PyAOS blog post and and PyCon shout-out to docs

**Comment by spencerahill** [comment]
v0.2 is out on PyPI and Github.  Still waiting for conda forge build to finish.  Once that does, I'll send out announcement emails and we'll call this done 😄

**Comment by spencerahill** [comment]
conda forge builds finished, announcements sent.  🎉 

@spencerkclark thanks for all your effort on this release.  Also thanks @darothen for your various comments...they were really helpful!  And thanks @chuaxr for patiently working through bugs with us and suggesting improvements.  We're thrilled to have you as an active user and hope to implement many of your suggestions in v0.3.

**Comment by spencerkclark** [comment]
Thanks for rolling this release out so quickly @spencerahill!  Cool to see you added a zenodo badge too.
