### ISSUE TITLE
Adding units/description to netcdf files

### ISSUE THREAD

**Issue by chuaxr** [spencerahill/aospy#201]
Currently, the descriptions/units in Var objects are not saved in the output netcdf files. It would be nice if this was the case.

**Comment by spencerahill** [comment]
Sure, I agree this would be nice, and it also should be relatively straightforward for us to implement.

Initial quick take: this will require adding a 'units' attribute to the DataArray somewhere in the `Calc` pipeline.  One catch is different units whether or not the output type is a vertical integral; that logic is handled here: https://github.com/spencerahill/aospy/blob/develop/aospy/calc.py#L457

**Comment by spencerkclark** [comment]
> One catch is different units whether or not the output type is a vertical integral

Indeed this is true; in the absence of more robust units support (e.g. with pint) there are more or less two options in this case:

1. Simply drop the units attribute
2. Append `'kg m^-2'` to the units attribute, which while dimensionally correct, might look a little strange for units that could be simplified.

**Comment by spencerahill** [comment]
>Append 'kg m^-2' to the units attribute, which while dimensionally correct, might look a little strange for units that could be simplified.

True, but I believe that's better than no units.  What about being explicit about the vertical integral operation?  E.g. `'(vertical integral of {0}): {0} kg m^-2)'.format(units)`.

**Comment by spencerkclark** [comment]
> True, but I believe that's better than no units.  What about being explicit about the vertical integral operation?  E.g. `'(vertical integral of {0}): {0} kg m^-2)'.format(units)`.

Sounds good to me!

**Comment by micahkim23** [comment]
I started looking at this issue and was planning on adding `attrs` to `data` in the `save` function https://github.com/spencerahill/aospy/blob/develop/aospy/calc.py#L669. The only weird thing is that `data` can either be an DataArray or OrderedDict.

```
OrderedDict([('globe', <xarray.DataArray ()>
array(1.0588634264346013e-05)
Coordinates:
    raw_data_start_date  datetime64[ns] 1678-01-01
    raw_data_end_date    datetime64[ns] 1681-01-01
    subset_start_date    datetime64[ns] 1678-01-01
    subset_end_date      datetime64[ns] 1680-12-31), ('tropics', <xarray.DataArray ()>
array(5.266911604961124e-06)
Coordinates:
    raw_data_start_date  datetime64[ns] 1678-01-01
    raw_data_end_date    datetime64[ns] 1681-01-01
    subset_start_date    datetime64[ns] 1678-01-01
    subset_end_date      datetime64[ns] 1680-12-31)])
```
In this case I add the units/description to each DataArray inside of the OrderedDict?

**Comment by spencerahill** [comment]
@micahkim23 I think we can avoid this if we add the metadata earlier in the pipeline.  E.g. before [this line](https://github.com/spencerahill/aospy/blob/develop/aospy/calc.py#L589) in `Calc.compute`.  I *think* the subsequent time and regional reductions will preserve the `attrs`.

**Comment by micahkim23** [comment]
@spencerahill When I add `attrs` to a Dataset, the Dataset gets the `attrs` but the DataArrays inside the Dataset don't get the `attrs`. Do you want me to add the `attrs` to the DataArrays inside the Dataset?

**Comment by spencerkclark** [comment]
@micahkim23 I think it would make the most sense if these attributes were added to *only* DataArrays (because the `units` and `description` attributes are variable-specific attributes).  Attributes of a Dataset can be thought of as more "global" attributes, in the sense that they apply to all the variables it contains.
