### ISSUE TITLE
TimeoutError in  TravisCI

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#219]
For the past week or so, we are now always getting a failure in exactly one Travis CI environment, but not always the same one -- I've seen in the 2.7, 2.7-min, and 3.6 ones so far.  These all are TimoutErrors in the ` test_submit_two_calcs_external_client` test.  See e.g. https://travis-ci.org/spencerahill/aospy/jobs/288531602

This feels like just something buggy on the Travis CI end, but it's still annoying.  Should look into and fix if we can.  In the meantime this issue serves at least as a heads up.

**Comment by spencerkclark** [comment]
It looks like the discussion in this issue might be related: https://github.com/dask/distributed/issues/1321.  Maybe we could try increasing the `death_timeout` when we start the `LocalCluster`?  I agree that it must have something to do with Travis; it's hard to predict whether this would be a sure-fire fix.

**Comment by spencerahill** [comment]
Thanks for looking that up.  https://github.com/dask/distributed/pull/1337, which was in response to that issue, is where the "Worker failed to start" logic was implemented.

>Maybe we could try increasing the death_timeout when we start the LocalCluster

Yes, that's a good idea.  

>it's hard to predict whether this would be a sure-fire fix.

I agree.  If it doesn't work I'll bring it up in the distributed repo.

**Comment by spencerkclark** [comment]
Alternatively, it seems just using the defaults for starting a `LocalCluster` in `test_automate.py` generates a cluster with 31 workers.  This is well more than we need; perhaps that could be what slows things down?

From the build log you linked to above: https://travis-ci.org/spencerahill/aospy/jobs/288531602#L810
