### ISSUE TITLE
Warn (or perhaps raise?) when the main script is constructed to submit zero calculations

### ISSUE THREAD

**Issue by spencerkclark** [spencerahill/aospy#253]
For instance if one forgets to specify `input_vertical_datatypes` and instead uses an empty list, the main script will run and silently compute nothing.  This is confusing for users who might not be familiar with the internals in `automate.py`, which create `Calc` objects based on the product of the input options (so if one option is an empty list, zero objects will be created).

**Comment by spencerahill** [comment]
I agree and expect this will be quite straightforward to implement.
