### ISSUE TITLE
Drop Python 2.7 support

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#256]
Xarray is planning on doing so by the end of 2018, c.f. https://github.com/pydata/xarray/issues/1830

So we'll need to do it no later than they do.  I'm fine with doing it earlier than that, provided it doesn't cause undue problems for our  users.  Are any of our current users using 2.7 and would be hard pressed to move to 3.x?  @chuaxr what are you using?

At the same time, I don't have any immediately pressing need to switch to only 3.x compatibility, so there's no need to rush.  @spencerkclark , do you have any ideas of what this could open up for us?  The only thing for me is if we one day get into type annotations, c.f. #81 , since the syntax is much cleaner for 3.x.  But that's very low priority.

A more immediate benefit would be simply one less CI environment to manage, which isn't trivial.

Related, we are dropping 3.4 shortly: #255

**Comment by spencerkclark** [comment]
@spencerahill there are no real game-changers that I can think of that are Python 3-only.  I agree though, not having to worry about cross-compatibility over CI will be a big benefit and type annotations could be nice (but I haven't played with them yet).

I'm all Python 3 these days, so I'm totally fine with dropping Python 2.7 support earlier too.  I'll double check with Jane the next time I see her to see what version she's using.

**Comment by chuaxr** [comment]
I've been using python 3.6, thanks for asking!
