### ISSUE TITLE
utils.io._robust_bool and utils.io.get_parent_attr are no longer used

### ISSUE THREAD

**Issue by spencerkclark** [spencerahill/aospy#264]
I was glancing at [a recent Coveralls build](https://coveralls.io/builds/16314863/source?filename=aospy%2Futils%2Fio.py) and noticed that we do not have test coverage for `utils.io._robust_bool` or `utils.io.get_parent_attr`.  A quick grep indicated that we do not use these functions internally within aospy anymore.  Is there a reason to keep them?

**Comment by spencerahill** [comment]
Good catch.  No reason that I can think of --- let's dump them.
