### ISSUE TITLE
Proposal: utils.longitude module and Longitude class

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#272]
In attempting to fix #229  via #266, I have repeatedly gotten myself totally confused regarding how to compare longitude values properly in a way that accounts for all of the potential edge cases of how individual longitudes and region boundaries can be represented.

As such, I have implemented a "brute force" approach: a module, `longitude.py`, and in it a class, `Longitude`, that addresses these concerns.  I posted it as a gist [here](https://gist.github.com/spencerahill/0594d42e815476276be52e74b7ce7870).  The included tests all pass on my machine.

The Longitude object enables unambiguous definition and comparison (via `==`, `<', `>', `<=`, and `>=` operator overloads) of longitude values.  It also has public methods for converting any longitude to the most common grids, -180 to 180 and 0 to 360. 

In addition to the direct target (which I still haven't done) of using this for Region masking, I think this could be useful functionality more generally for people outside the main script pipeline.  However, this cuts against our approach of late, which has been pruning the non-essential bits.

So I wanted to see how people feel about this: good idea, bad idea, suggestions, don't understand, anything.

**Comment by spencerahill** [comment]
In order to use the `Longitude` class for determining region masks, the logic would be as follows:

- If a Region object has `Longitude(west_bound) < Longitude(east_bound)` (i.e. `west_bound` is less than `east_bound` with respect to a -180 to 180 grid), then mask out points with `Longitude(point) < west_bound or Longitude(point) > east_bound`.
- Conversely, if `Longitude(west_bound) < Longitude(east_bound)` (i.e. the region crosses the dateline), then mask out points with `Longitude(point) > west_bound and Longitude(point) < east_bound`

One design decision that I haven't made yet is how to operate on arrays with `Longitude`; the logic I've implemented so far is for scalars only.  What is the most idiomatic approach that doesn't incur a big performance hit?  @spencerkclark you've worked with `xr.apply_ufunc` a lot; is that a potentially useful tool here?

I suppose I'm guilty here of optimizing prematurely; I can just implement this as a simple loop or list comprehension and then go from there.

**Comment by spencerkclark** [comment]
@spencerahill sorry I haven't had a chance to look at this deeply.  At first glance it looks very cool!  

> One design decision that I haven't made yet is how to operate on arrays with Longitude; the logic I've implemented so far is for scalars only.

In a little playing around, I've noticed that if you compare an array-like object to a `Longitude` object things appear to work (however, going the other way, i.e. `Longitude` object to array, does not).  See this short [gist](https://gist.github.com/spencerkclark/6b6e8fb2aea401dd4449a35bf1466362) as an example.  That said, I'm guessing you're looking for something more robust?  Let me think about it more over the next few days.

**Comment by spencerahill** [comment]
>In a little playing around, I've noticed that if you compare an array-like object to a Longitude object things appear to work (however, going the other way, i.e. Longitude object to array, does not). See this short gist as an example.

Ah good call!  Didn't even occur to me to try.  I'll play around with the operator overload implementation to get that working.

**Comment by spencerahill** [comment]
Numpy's operator functions like `np.less` are super useful here.  I updated the Gist using those, so that comparison with arrays should now work.

So now that this is working, @spencerkclark, maybe before worrying about performance as I initially asked, do you think this is a good approach otherwise?  If so, I'll include it in #266 and we can iterate from there.

It's ok if you you're not sold on it...I learned a decent amount about operator overloading, properties, and other OOP stuff from this little exercise.

**Comment by spencerkclark** [comment]
> Numpy's operator functions like np.less are super useful here. I updated the Gist using those, so that comparison with arrays should now work.

Very cool!  Yeah I think it's a pretty elegant approach to the problem; I say go ahead and pursue it in #266.

**Comment by spencerahill** [comment]
Closed in #266
