### ISSUE TITLE
Decide what to do with eddy-related functionality in Calc

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#274]
2.5 years ago I implemented support for "eddy" fields, meaning the anomalies of a field with respect to it's monthly mean.  And likewise for the zonally asymmetric component of fields, i.e. the difference between a field's full value and its zonal mean value.  All of the related code is in `Calc`.

This code is quite convoluted and hackish.  It also is not even documented at all in our official docs, nor can I remember the last time I used it...probably not since right after I implemented it!  It's also now complicating our efforts to switch to the newly available CFTimeIndex (see https://github.com/spencerahill/aospy/pull/273#issue-189192781).  So we should decide what to do with it.

In my opinion, the best course of action would be to simply strip it all out for now and then re-implement it in a non-cringe-worthy way if/when the use case arises.  But if others (@spencerkclark, @chuaxr) are using it, we could leave it for now.

**Comment by chuaxr** [comment]
I don't use the eddy feature, but thanks for the heads-up!

**Comment by spencerahill** [comment]
Thanks @chuaxr.

So the plan moving forward is to just remove this stuff for now and re-implement it later if/when it arises as a compelling feature to have.

That being said, I would say removing this is neither a high priority nor exactly straightforward to do, since the relevant code is so convoluted (mea culpa).  Could be wrong on the second part though.
