### ISSUE TITLE
Update lon and lat bounds of example in our docs

### ISSUE THREAD

**Issue by jdossgollin** [spencerahill/aospy#294]
The file at https://github.com/spencerahill/aospy/blob/develop/aospy/examples/example_obj_lib.py defines `west_bound`, `east_bound`, etc but the examples (and working code) defines `lon_bounds` and `lat_bounds`

**Comment by spencerkclark** [comment]
@spencerahill recently made some significant improvements to the Region logic (#266), which are reflected in the latest source code on GitHub.  However we are long overdue for a new release (the last release was over a year ago now), so the version of aospy on conda-forge/PyPI doesn't reflect these changes.

I know @spencerahill has mentioned to me offline that he would like to cut a new 0.3 release once #289 is merged, though progress there has stalled a bit.  For that reason, it might be worth doing a 0.2.1 release in the meantime just to sync things up.  @spencerahill, what do you think?

**Comment by spencerahill** [comment]
Thanks for catching this @jdossgollin 

Yes, @spencerkclark, we should do a 0.2.1 release.  Realistically I can get to that in the second half of this month.

We should also improve how our docs are generated such that the default page is for the latest stable release, rather than from the develop branch.  Should be easy enough to do as part of 0.2.1.

**Comment by jdossgollin** [comment]
OK -- I'll let you guys decide whether to close this issue but I don't need to keep it open

**Comment by spencerahill** [comment]
We'll leave it open until we actually go ahead with the release, in case anybody stumbles across the same problem between now and then.

**Comment by spencerahill** [comment]
v0.3 release done and new docs are up, so closing this
