### ISSUE TITLE
Towards v0.3 release

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#307]
Although I haven't finished #289, I think we now have more than enough new features and breaking changes to merit a v0.3 release.  I can turn around a quick v0.3.1 release once I finish #289.

Realistically I can probably get to this not this week but sometime in the following couple weeks.  But I'd say it's worth waiting on the pending PRs by @jdossgollin.  @jdossgollin, think you can manage to wrap those up in the next week or so?

**Comment by jdossgollin** [comment]
Yes -- tonight or tomorrow (knock on wood 😄)

**Comment by spencerahill** [comment]
In doing this release, I will also fix #308

**Comment by spencerkclark** [comment]
It looks like we'll need to update the pinned versions in `docs/environment.yml` for the documentation to build:
https://readthedocs.org/projects/aospy/builds/8102985/

**Comment by spencerahill** [comment]
>It looks like we'll need to update the pinned versions in docs/environment.yml for the documentation to build

Yes, just realized that.  Have pushed commits that hopefully fix that.

**Comment by spencerahill** [comment]
Those commits are basically copying https://github.com/pydata/xarray/pull/2310

I'm just committing them to master directly rather than as PRs since this is all just to fix the docs

**Comment by spencerahill** [comment]
The v0.3.0 release is done on github and on pip.  I'm having a little trouble getting our feedstock updated for the release on conda; waiting for help from the conda-forge folks on that.

For the docs, there are the following problems: 
- the 'stable' and 'latest' builds are completing, but 'stable' is still only showing v0.2 rather than v0.3
- the 'v0.3.0' build is failing, because of the incorrect settings in docs/environment.yml noted above.  I'm not sure how to fix that, since the release has already been made.

Once we resolve all these things and we're up on conda-forge, I'll make the release email announcements

**Comment by spencerkclark** [comment]
> the 'v0.3.0' build is failing, because of the incorrect settings in docs/environment.yml noted above. I'm not sure how to fix that, since the release has already been made.

Hmm...this one is tricky.  Is it considered bad practice to [delete a release](https://help.github.com/articles/editing-and-deleting-releases/) and redo things?

**Comment by spencerahill** [comment]
>Is it considered bad practice to delete a release and redo things?

Good thinking.  That may be the only way to go.  I'll ask the RTD people first to see if there's a less intrusive option.

---

Regarding conda: v0.3.0 builds are up, but our build matrix is incorrect; we have 2.7(!) and 3.6 builds, rather than 3.6 and 3.7.  That's likely an easy fix, I'm just a bit confused right now, and it's being sorted out here: https://github.com/conda-forge/aospy-feedstock/issues/14

**Comment by spencerahill** [comment]
RTD issue for the doc builds here: https://github.com/rtfd/readthedocs.org/issues/4905

**Comment by spencerahill** [comment]
From https://github.com/rtfd/readthedocs.org/issues/4905#issuecomment-439138090, RTD can't do anything

I think deleting the release is unnecessary.  Standard procedure here would be to just push out  v0.3.1 release to fix this.  Barring objections that's what I'll do.

That actually works out well anyways with resolving the conda build matrix; I'll make sure we're set for the proper builds on conda before making the release.

We should also add something to the HOW_TO_RELEASE or maybe even a proper test to ensure we (I) don't make this mistake again on future releases.  (Might also add a section to HOW_TO_RELEASE about the feedstock stuff)

**Comment by spencerkclark** [comment]
> I think deleting the release is unnecessary. Standard procedure here would be to just push out v0.3.1 release to fix this. Barring objections that's what I'll do.  That actually works out well anyways with resolving the conda build matrix; I'll make sure we're set for the proper builds on conda before making the release.

Yeah that makes sense.  The only potential drawback is that we'll have a broken link to version 0.3.0 of the documentation, but I guess we can live with that (deleting the release could cause more unforeseen issues).  Hopefully there will be many more releases of aospy in the future, so that link will get pushed further and further back :)

![screen shot 2018-11-15 at 4 47 20 pm](https://user-images.githubusercontent.com/6628425/48583849-3135ac00-e8f6-11e8-858e-598af979907e.png)

**Comment by spencerahill** [comment]
There is an option within RTD to make branches 'active' or 'inactive', and I *think* if I just set the v0.3.0 to inactive then it won't show up anymore.

**Comment by spencerahill** [comment]
Conda builds are fixed:

```
conda search aospy
Loading channels: done
# Name                  Version           Build  Channel
aospy                       0.1          py27_0  conda-forge
aospy                       0.1          py35_0  conda-forge
aospy                       0.1          py36_0  conda-forge
aospy                     0.1.1          py27_0  conda-forge
aospy                     0.1.1          py27_1  conda-forge
aospy                     0.1.1          py34_1  conda-forge
aospy                     0.1.1          py35_0  conda-forge
aospy                     0.1.1          py35_1  conda-forge
aospy                     0.1.1          py36_0  conda-forge
aospy                     0.1.1          py36_1  conda-forge
aospy                     0.1.2          py27_0  conda-forge
aospy                     0.1.2          py35_0  conda-forge
aospy                     0.1.2          py36_0  conda-forge
aospy                       0.2          py27_0  conda-forge
aospy                       0.2          py35_0  conda-forge
aospy                       0.2          py36_0  conda-forge
aospy                     0.3.0          py27_0  conda-forge
aospy                     0.3.0          py36_0  conda-forge
aospy                     0.3.0          py36_1  conda-forge
aospy                     0.3.0          py37_1  conda-forge
```

So I'll go ahead with the 0.3.1 release in the coming days, after updating HOW_TO_RELEASE and adding a test for the docs build.

**Comment by spencerahill** [comment]
With #314 in, we're all set for v0.3.1.  Most likely will have time for it before the Thanksgiving holiday.

**Comment by spencerahill** [comment]
Done! 🎉
