### ISSUE TITLE
Land mask not being applied to regional calculations

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#37]
For example, global, global-land, and global-ocean regions ('globe', 'land', and 'ocean' in my obj-lib) are all identical.  Not sure for how long this has been the case.

(Good example of why not having automated tests causes problems.)

**Comment by spencerkclark** [comment]
~~There's something unusual going on now with masking in general -- when I'm doing a global average for some reason it's masking the entire array.  Looking into it now...~~

**Update** Never mind, it was an issue with my object library -- I wasn't aware the `lat_bnds` and `lon_bnds` keywords in Region were changed to `lat_bounds` and `lon_bounds`.

**Comment by spencerahill** [comment]
Cool.  Sorry, might have forgotten to mention that.  Also, hopefully you caught the switch from `land_mask` to `do_land_mask` in `Region.__init__`.

So we can close this?

**Comment by spencerkclark** [comment]
No worries, I saw the part about the change to the `land_mask` kwarg in the commit message.  I'm glad you ended up changing the bounds keywords to match the internals as well (even if I wasn't aware of it at first).  Go ahead and close it!
