### ISSUE TITLE
Solution needed for Model-dependent Calc functions

### ISSUE THREAD

**Issue by spencerkclark** [spencerahill/aospy#44]
An issue I've encountered, particularly for more involved calculations which involve many variables, is that the way the calculation needs to be carried out varies depending on the model used.  For a concrete example take computing the net column heating due to radiative, sensible, and latent heat fluxes.  In a comprehensive GCM (like AM2) there is a term due to reflected shortwave radiation (swup_toa); this does not exist in the gray-atmosphere idealized moist model.  In addition there are differences in how to handle the evaporative heat flux from the surface in each Model.  Currently I address this by creating two separate calc functions and two separate variables linked with each calc function.  This is rather inefficient, and I end up with two differently named variables representing the same physical quantity. 

Another somewhat related situation that I encounter is that in some cases a variable is already computed in the model, while in others a variable needs to be computed from other variables.  This is especially tricky to deal with when that variable is involved in another function; again I need to create separate functions and variables for each Model.

I'm not aware of any current (or numpy-legacy) infrastructure that is (was) in place that works to address this issue.  I don't have a particularly good solution to either of these problems in mind at the moment -- I'll add one here if I think of one, but I just wanted to raise this issue while we are thinking about the next refactor of the object library.

**Comment by spencerahill** [comment]
I'm going to close this and suggest we continue the discussion on #3, since that's largely about the same issue.
