### ISSUE TITLE
Resolving problems stemming from xray -> xarray transition

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#53]
A few problems for aospy have come up relating to the xray to xarray transition.
- Can't rename a dimension to it's existing name: https://github.com/pydata/xarray/issues/724
- The new xarray data model causes our `aospy.utils.replace_coord` function to break: https://github.com/pydata/xarray/issues/725

Both of them have workarounds that I've implemented in 38d2bcb.  The workaround for the latter is especially untenable in the long run, because the metadata for phalf gets kept for a pfull array.  So I'll leave this open to remind us to resolve them once they get fixed on the xarray side (or if we keep up with something smarter in the meantime).

**Comment by spencerkclark** [comment]
:+1: I finally got around to updating to the latest release of xarray today; many thanks for these edits, and reaching out on the xarray side of things.

**Comment by spencerahill** [comment]
No problem...I stumbled across these while trying to implement some upwind advection schemes.  In so doing, I decided to cleanup infinite-diff by using the xarray bug fixes, which led me down the rabbit hole :)

FYI I've now switched the `replace_coord` workaround with Stephan's suggestion of `to_dataset`.

**Comment by spencerahill** [comment]
https://github.com/pydata/xarray/pull/736 solves the rename problem, so we can implement that after the next xarray release.

**Comment by spencerahill** [comment]
https://github.com/pydata/xarray/pull/750 fixes the replece_coord problem, and has been included in xarray's 0.7.1 release, so we can now implement both these.  I will do so some time soon-ish.

**Comment by spencerahill** [comment]
Both fixed in xarray 0.7.2 and implemented in #74.
