### ISSUE TITLE
Backend for to_netcdf

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#69]
@spencerkclark, could you tell (remind?) me of the motivation behind using the `engine=scipy` specification for our netcdf I/O  in `calc.py`?  Just curious.

**Comment by spencerkclark** [comment]
Sure, no problem.  This is related to the concerns of #58.  I found that when using the default engine (`engine='netcdf4'`), ncview would not recognize files saved through xarray (incidentally ncdump works fine in either case).  When using the `engine='scipy'` ncview works OK.

E.g. this is the error message from ncview I get for a dataset serialized with the netcdf4 engine.  This exact dataset gets serialized to a file that can be opened without issues using ncview if I set `engine='scipy'`.

```
py27 []: ncview test_netcdf4.nc
Ncview 1.93b David W. Pierce  25 May 2006
http://meteora.ucsd.edu:80/~pierce/ncview_home_page.html
Copyright (C) 1993 through 2006, David W. Pierce
Ncview comes with ABSOLUTELY NO WARRANTY; for details type `ncview -w'.
This is free software; type `ncview -c' for redistribution details.

ncopen: filename "test_netcdf4.nc": Not a netCDF file
```

Perhaps this is an issue with the version of ncview I'm using?  It seems as though the `netcdf4` engine [does do some more advanced compression](http://xarray.pydata.org/en/stable/io.html?highlight=engine#chunk-based-compression) than the `scipy` engine; maybe that's what is tripping things up?  Can you replicate this issue on your end?

E.g. try ncview on `/home/skc/test_netcdf4.nc`, versus `/home/skc/test_scipy.nc`.

**Comment by spencerahill** [comment]
Cool, thanks!  Yes, I can reproduce this.  Moreover, I have the latest ncview version installed on my mac (via homebrew), and it renders either file without error.

For aospy purposes, in the long run I think using the most up-to-date engines/netcdf versions is the way to go, but ultimately I don't think it's worth messing with for now.  Maybe when GFDL updates ncview :)

**Comment by spencerkclark** [comment]
For sure, perhaps we could make this an option in the configuration?  Similar to `LAT_STR` etc., we could have a variable that sets the engine used in saving files in one place.  We could simply note that by default aospy would use the `netcdf4` engine, but for older versions of command line tools we recommend using the `scipy` engine (and this would give the user the option of setting it without digging too deep into the code).

Not high priority, but just a thought for the future.

**Comment by spencerahill** [comment]
:+1:

**Comment by spencerahill** [comment]
@spencerkclark is this still an issue for you?  As part of #112, I was hoping to pare down on the dependencies; this is the only place that requires scipy.

No worries either way -- it's not a huge deal to have scipy as a dependency.

**Comment by spencerkclark** [comment]
Yes, it remains an issue for me; however, I think if I issue a helpdesk ticket, GFDL might go ahead and update the system ```ncview``` (considering their version is over 10 years old, I think it's about time).  That or I may find a way to do a site install from scratch.

I say go ahead and use the ```netcdf4``` backend in favor of reducing dependencies.

**Comment by spencerahill** [comment]
No, we'll leave it in...not worth messing up your workflow.  Likely that others will be stuck with old ncview versions also.

Long term this should be a configurable setting, as discussed already.

**Comment by spencerkclark** [comment]
Regarding a "set options" solution, xarray and dask both have a nice simple way of doing this:

https://github.com/pydata/xarray/blob/master/xarray/core/options.py#L12
https://github.com/dask/dask/blob/master/dask/context.py#L12
