### ISSUE TITLE
Data saving to /archive not working

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#70]
By chance, I just noticed that saving to archive has not been happening (for my runs at least) for quite some time -- none of the data.tar files of mine on /archive have been updated since this summer.  So the source of this probably originates from around then (the latest date I have is August 27).

@spencerkclark, is this the case for you too?  It is possible I modified something within my aospy-obj-lib, and aospy itself is working fine.

I/O to scratch is working fine (which is why I didn't notice this for so long!).

**Comment by spencerkclark** [comment]
Yes, this is true for me as well.  I think this may have gotten lost in the shuffle during the numpy to xarray transition.  Hopefully it's a simple fix.

**Comment by spencerahill** [comment]
Ok, thanks.  My gues is it's simple enough, just faulty logic within save_to_archive.  Not a priority, but I will get to it eventually.

**Comment by spencerkclark** [comment]
Is it simply that we don't pass `archive=True` in the only call to `calc.save()`?

See https://github.com/spencerahill/aospy/blob/develop/aospy/calc.py#L714

**Comment by spencerahill** [comment]
Ha ya I think that's it!  Let me give that a try.

**Comment by spencerahill** [comment]
Yes, that was the problem.  I'll add some tests before pushing a fix (although not a priority).  You can just add `archive=True` for the time being.  Thanks!  Good catch.

**Comment by spencerahill** [comment]
Fixed by #74 (in 6fc9e9e)
