### ISSUE TITLE
For 'gfdl_repo' and 'one_dir' data, missing data silently ignored

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#72]
If a date range is specified but the data is only found for a subset of that range, computations are performed on the available data without any indication of the incorrect range, _and_ when saved to disk the label incorrectly indicates the full specified range.  

For example, If I ask for 1979-2008 averages on this precipitation data: /archive/pcmdi/repo/CMIP5/output/NSF-DOE-NCAR/CESM1-CAM5/amip/mon/atmos/Amon/r1i1p1/v20120612/pr/pr_Amon_CESM1-CAM5_amip_r1i1p1_197901-200512.nc, the output will be saved as 1979-2008 despite the data stopping at 2005.

Should be straightforward to fix -- just requires adding some checks and raising an exception.

**Comment by spencerkclark** [comment]
Tangentially related, but does this mean you've worked out spencerahill/aospy-obj-lib#10?

**Comment by spencerahill** [comment]
Yes; see update to that issue (with apologies for not much detail).  But I've been performing calculations on CMIP5 `amip` and `amip4K` runs for the past several weeks.

**Comment by spencerahill** [comment]
Also as an aside the data originally referenced in this issue is bad, both for `amip` and `amip4K`: http://www.cesm.ucar.edu/CMIP5/errata/

**Comment by spencerkclark** [comment]
> If a date range is specified but the data is only found for a subset of that range, computations are performed on the available data without any indication of the incorrect range, and when saved to disk the label incorrectly indicates the full specified range.

I recently encountered this for files retrieved under the `'one_dir'` paradigm as well, so we should make sure the fix for this issue we settle on addresses both `'gfdl_repo'` and `'one_dir'`.

**Comment by spencerkclark** [comment]
Closed by #90
