### ISSUE TITLE
Prevent Empty Header error when two processes try to write to same .tar file

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#75]
Sometimes I will have aospy computing things at the same time on multiple analysis nodes (or the same node but from different terminal sessions).  This often produces low-level errors when writing the data to the /archive data.tar files, e.g. "Empty header file".  I think it's simply a result of one session trying to access/modify the tar file at the same time as another one.

There should be some way of implementing a lock to prevent this from happening.  How to test seems more tricky.

**Comment by spencerahill** [comment]
This is becoming more of an issue now that we have Calcs fired off in parallel.  I just tried submitting a main script that specified 4 variables computed in 4 different runs in a single model, and 3/3 times I tried it I got either the empty header file error or a string of "tar: Deleting non-header from archive" messages interspersed with a few "tar: Exiting with failure status due to previous errors", ultimately ending in "tarfile.ReadError: bad checksum"

@spencerkclark has this ever happened to you?  Googling the error messages didn't lead to anything immediately helpful.

**Comment by dboeckenhoff** [comment]
I have the same problem with a similar usecase. Have you encountered any solution yet?

**Comment by spencerahill** [comment]
Unfortunately I have not, in part because I haven't spent any time on this since the last post.  I just did a bit of googling, and [this SO post](https://stackoverflow.com/questions/489861/locking-a-file-in-python) seems to be a useful starting point.  This is assuming that I'm correct that we need a "lock" of some kind -- frankly I'm pretty ignorant here.  

Is your usecase when using aospy or no?  If not, you might look into this [FileLock](https://github.com/dmfrey/FileLock) package listed in the above link.  For aospy, we'll have to think about the design.

@spencerkclark, any ideas on this?

**Comment by spencerkclark** [comment]
I think this is the root cause of some intermittent test failures in the CI https://github.com/spencerahill/aospy/pull/180#issuecomment-300133662 , so it would be good to solve this once and for all.

@spencerahill I too have not thought much about how to fix this.  That FileLock package seems like it could be a nice simple solution, but I agree we'll have to think about it more for aospy.

**Comment by spencerahill** [comment]
Or can we use something in the standard library, e.g. something within asyncio?  Or something in dask?

This feels hackish, but one could put a try/except clause within a loop, with a pause between each attempt and a maximum number of attempts:

```python
max_attempts = 10
for i in range(max_attempts):
    try:
        # <insert logic for writing to .tar>
    except HeaderError as e:  # or whatever the exception class is
        err_msg = e
        time.sleep(1)
    else:
        break
else:
    raise HeaderError(err_msg)
```

(Not necessarily advocating this; just popped into my head)

**Comment by spencerahill** [comment]
Just toyed around with this for a while but was unsuccessful in reproducing the error in an easy way.  Namely, I tried opening the same .tar file from multiple Python sessions at once, each in append ('a') mode.  But it didn't raise.  Have to let this go for now, but will leave for reference some further notes on this:

Based on the stack trace in an error log from [a recent AppVeyor build](https://ci.appveyor.com/project/spencerahill/aospy/build/1.0.271/job/vhaboyfdrarg3fk9#L486) that failed because of this, [this line](https://github.com/python/cpython/blob/master/Lib/tarfile.py#L1495) within tarfile.Tarfile.__init__ is where the exception is being thrown.  It means that the `tarinfo = self.tarinfo.fromtarfile(self)` line above is throwing a HeaderError.  `self.tarinfo` is the `TarInfo` class.  So the error is occuring in the [`TarInfo.fromtarfile`](https://github.com/python/cpython/blob/master/Lib/tarfile.py#L1087) method.

**Comment by spencerkclark** [comment]
@spencerahill do you think we can close this in light of #197?  (We can always re-open it if we want to revisit things).

**Comment by spencerahill** [comment]
Yes let's close!
