### ISSUE TITLE
Decide on docstring formatting

### ISSUE THREAD

**Issue by spencerahill** [spencerahill/aospy#79]
We will definitely use Sphinx, so it's a question of what flavor.  Namely, numpy has its own conventions: https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

It also looks like xarray uses it: https://github.com/pydata/xarray/blob/master/xarray/core/alignment.py#L49

And @spencerkclark, I've seen from prior docstrings you've written that you use it, right?

So maybe that's the path of least resistance?  I have written a few docstrings in the past using the standard sphinx syntax, but I am 100% ok switching.

**Comment by spencerkclark** [comment]
Yes, I'm most familiar with numpy style docstrings -- but I'll admit, I'm not sure what the pros and cons of the different flavors are.  Prior to working on aospy I started using the numpy flavor for the simple reason that I saw others in the scientific community doing it.  All I can really find online is that numpydoc contains ["several custom extensions to Sphinx"](https://github.com/numpy/numpydoc/blob/master/README.rst) (so maybe it has some added functionality?).  

I have not used standard Sphinx syntax extensively -- is there anything that stands out to you in the [numpydoc instructions](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt) that seems like something you can't do in standard Sphinx?

**Comment by spencerahill** [comment]
Thanks.  I'm sure if it's good enough for Numpy it will be good enough for us.

Numpy-style it is!
