### ISSUE TITLE
Restore original datetime metadata upon saving output

### ISSUE THREAD

**Issue by spencerkclark** [spencerahill/aospy#94]
Currently, if we encounter time dimensions referenced to a date prior to 1678-01-01, we automatically offset things internally such that the dates aospy sees all begin at 1900-01-01 (this is to account for restrictions in `pandas`).  When we save computational results to netCDF files, however, we do not currently restore datetime metadata to match the way things were in the initial run (so output netCDF files look as though things started in 1900 as well).  This may amount to simply saving the initial units attribute of the time variable when reading in the file, and resetting it to the initial value when we save data.

In addressing this issue I think we should also consider changing the offset reference date to 1678-01-01 to allow the maximum available `pandas` / `np.datetime64` compatible time range.

**Comment by spencerahill** [comment]
> In addressing this issue I think we should also consider changing the offset reference date to 1678-01-01 to allow the maximum available pandas / np.datetime64 compatible time range.

This is addressed in #97.

But otherwise yes this would be good to implement and I doubt too difficult.  Although since it's not urgent, maybe it's better to do as part of the Calc refactor, whenever we get to that portion of Calc.

**Comment by spencerahill** [comment]
@spencerkclark is this in place yet or no?  Please close if yes.

**Comment by spencerahill** [comment]
@spencerkclark where do we currently stand on this?  (I'm in the process of culling obsolete Issues as part of #206)

**Comment by spencerkclark** [comment]
@spencerahill it has not been resolved; it's something that would be nice to do, given our current workaround for dates pre-1678, but not necessarily super high priority.  (It might be a low-hanging fruit though).

**Comment by spencerahill** [comment]
Cool, thanks.  `subset_` and `raw_data_{start,end}_date` are written to output netCDF files currently, but these alone can't be used to infer the original dates.  Still I agree, should be relatively straightforward.
